# Generated by Django 5.2.8 on 2026-03-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CollectionMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="Stable key used by UIs, e.g. 'canadian-immigration'.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name for this collection.",
                        max_length=200,
                    ),
                ),
                (
                    "ionos_collection_id",
                    models.CharField(
                        help_text="IONOS collection/ index UUID.",
                        max_length=128,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        help_text="Optional list/dict of topical tags.",
                        null=True,
                    ),
                ),
                (
                    "trust_score",
                    models.FloatField(
                        default=0.0,
                        help_text="0–1 score expressing overall source reliability.",
                    ),
                ),
                ("last_ingest_at", models.DateTimeField(blank=True, null=True)),
                ("doc_count_snapshot", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
