# Generated by Django 5.2.12 on 2026-03-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_collections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionmetadata',
            name='ionos_collection_id',
            field=models.CharField(db_index=True, help_text='IONOS collection/ index UUID.', max_length=128),
        ),
    ]
